### ISSUE TITLE
Not able to make correct suggestion

### ISSUE THREAD

**Issue by debashish2014** [oranoran/antlr4-autosuggest-js#1] opened 2017-12-29 08:07 UTC
Hi, 

I am using the following Test.G4, which is a very simple grammar for variable declaration.

grammar Test;

file:   (varDecl)+ EOF;

varDecl
    :   type ID '=' NUMBER ';'
    ;

type:   'float' | 'int' | 'decimal' ; // user-defined types

ID  :   LETTER (LETTER | [0-9])* ;

NUMBER: DIGIT+;

fragment LETTER : [a-zA-Z] ;

fragment DIGIT : [0-9];

SPACES
 : [ \u000B\t\r\n] -> channel(HIDDEN)
 ;

Ideally, if a user types "int a", then the expected suggestions will be '=', but it is not finding any suggestion. Anything wrong here?

**Comment by oranoran** [comment] 2017-12-31 22:11
@debashish2014, thanks for reporting. I found & fixed the root cause. Will push and publish an update soon, pending a final review of the code.

**Comment by oranoran** [comment] 2018-01-01 14:11
@debashish2014, version 0.2.2 has been built with this fix. Will close the issue in the next few days unless you report any further issues.

**Comment by debashish2014** [comment] 2018-01-02 09:01
Hi @oranoran , Thank you for the fix. I will test and verify.

**Comment by debashish2014** [comment] 2018-01-02 09:53
Hi @oranoran , Thank you so much for authoring such a wonderful project.  The issue has been fixed for the Test.G4.  

However, I wrote another grammar file for testing as shown below, which unfortunately is not working. If user types 'SHOW EMPLOYEE' or 'SELECT EMPLOYEE' then the suggestion should be 'FOR' and 'WHERE'.

grammar autocomplete;

query
 : query_stmt EOF
 ;

query_stmt
: start_keyword  literal_name  filter_name
;

filter_name
 : 'FOR'
 | 'WHERE'
 ;

start_keyword
: 'SHOW'
| 'SELECT'
;

literal_name
: IDENTIFIER
;

IDENTIFIER: LETTER (LETTER | [0-9])*;

SPACES
 : [ \u000B\t\r\n] -> channel(HIDDEN)
 ;

UNEXPECTED_CHAR
 : .
 ;

fragment DIGIT : [0-9];

fragment LETTER : [a-zA-Z] ;

**Comment by oranoran** [comment] 2018-01-02 10:03
Thanks @debashish2014!
Can you create a new issue for this? I will close this one and check out the new issue.

**Closed as completed by oranoran** 2018-01-02 10:03 UTC
Labels: bug, fixed

**Comment by debashish2014** [comment] 2018-01-02 10:10
Sure thing. Will do.
